In [3]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Chenna", "Kesava", "Reddy"],
    "Department": ["IT", "IT", "HR", "HR", "IT", "HR"],
    "Salary": [50000, 60000, 40000, 45000, 70000, 55000],
    "state": ['Bangalore','HYD','chennai','HYD','Bangalore','HYD']
}

df = pd.DataFrame(data)
result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean", "min", "max"]
)
result2 = df[df["Department"] == "IT"].loc[
    lambda x: x["Salary"] == x["Salary"].max(),
    ["Name", "Salary"]
]
result3 = df.loc[
    df.groupby("state")["Salary"].idxmax(),
    ["Name", "state", "Salary"]
]
#result4 = df.loc[
   # df.groupby("State")["Salary"].idxmax(),
   # ["Name", "State", "Salary"]
#]

print(result)
print(result3)
print(result)
print(result)
print(result2)
#print(result4)
print(result.loc[["IT"]])
#print(df)

                    mean    min    max
                  Salary Salary Salary
Department
HR          46666.666667  40000  55000
IT          60000.000000  50000  70000
      Name      state  Salary
4   Kesava  Bangalore   70000
1      Bob        HYD   60000
2  Charlie    chennai   40000
                    mean    min    max
                  Salary Salary Salary
Department
HR          46666.666667  40000  55000
IT          60000.000000  50000  70000
                    mean    min    max
                  Salary Salary Salary
Department
HR          46666.666667  40000  55000
IT          60000.000000  50000  70000
     Name  Salary
4  Kesava   70000
               mean    min    max
             Salary Salary Salary
Department
IT          60000.0  50000  70000

In [7]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Chenna", "Kesava", "Reddy"],
    "Department": ["IT", "IT", "HR", "HR", "IT", "HR"],
    "Salary": [50000, 60000, 40000, 45000, 70000, 55000],
    "state": ['Bangalore','HYD','chennai','HYD','Bangalore','HYD']
}
df = pd.DataFrame(data)

print(df[["Name", "Salary"]])

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   40000
3   Chenna   45000
4   Kesava   70000
5    Reddy   55000

In [8]:
df.loc[:, ["Name", "Salary"]]

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   40000
3   Chenna   45000
4   Kesava   70000
5    Reddy   55000

In [9]:
result = df[df["Salary"] > 60000]

print(result)

     Name Department  Salary      state
4  Kesava         IT   70000  Bangalore

In [13]:
#Below is the code to filter the rows where the salary is between 50000 and 70000.
result = df[df["Salary"].between(50000, 70000)]

print(result)

     Name Department  Salary      state   Bonus
0   Alice         IT   50000  Bangalore  5000.0
1     Bob         IT   60000        HYD  6000.0
4  Kesava         IT   70000  Bangalore  7000.0
5   Reddy         HR   55000        HYD  5500.0

In [12]:
#Bonus calculation.
df["Bonus"] = df["Salary"] * 0.10
print(df)

      Name Department  Salary      state   Bonus
0    Alice         IT   50000  Bangalore  5000.0
1      Bob         IT   60000        HYD  6000.0
2  Charlie         HR   40000    chennai  4000.0
3   Chenna         HR   45000        HYD  4500.0
4   Kesava         IT   70000  Bangalore  7000.0
5    Reddy         HR   55000        HYD  5500.0

In [ ]:
#update the salary of all employees by adding 5000 to their current salary.
df["Salary"] = df["Salary"] + 5000
print(df)

      Name Department  Salary      state   Bonus
0    Alice         IT   60000  Bangalore  5000.0
1      Bob         IT   70000        HYD  6000.0
2  Charlie         HR   50000    chennai  4000.0
3   Chenna         HR   55000        HYD  4500.0
4   Kesava         IT   80000  Bangalore  7000.0
5    Reddy         HR   65000        HYD  5500.0

In [ ]:
#Drop the Bonus column from the DataFrame.
df.drop("Bonus", axis=1, inplace=True)
print(df)

      Name Department  Salary      state
0    Alice         IT   60000  Bangalore
1      Bob         IT   70000        HYD
2  Charlie         HR   50000    chennai
3   Chenna         HR   55000        HYD
4   Kesava         IT   80000  Bangalore
5    Reddy         HR   65000        HYD

In [ ]:
#Drop the first row from the DataFrame.
df1=df.drop(0, axis=0)
print(df1)

      Name Department  Salary      state
1      Bob         IT   70000        HYD
2  Charlie         HR   50000    chennai
3   Chenna         HR   55000        HYD
4   Kesava         IT   80000  Bangalore
5    Reddy         HR   65000        HYD

In [24]:
#Sort the DataFrame by the "Salary" column in ascending order.
df.sort_values("Salary")
ss=df.sort_values("Salary", ascending=False)
print(ss)

      Name Department  Salary      state
4   Kesava         IT   80000  Bangalore
1      Bob         IT   70000        HYD
5    Reddy         HR   65000        HYD
0    Alice         IT   60000  Bangalore
3   Chenna         HR   55000        HYD
2  Charlie         HR   50000    chennai

In [ ]:
#Increase the salary of all employees by 10% using the apply() function.
s=df["Name"].str.upper()
print(s)

0      ALICE
1        BOB
2    CHARLIE
3     CHENNA
4     KESAVA
5      REDDY
Name: Name, dtype: object

In [ ]:
#Increase the salary of all employees by 10% using the apply() function.
chenna=df["Salary"] = df["Salary"].apply(lambda x: x * 1.10)
print(chenna)

0    66000.0
1    77000.0
2    55000.0
3    60500.0
4    88000.0
5    71500.0
Name: Salary, dtype: float64

In [27]:
#Increase the salary of all employees by 10% using a custom function.
def increase_salary(x):
    return x * 1.10

emp=df["Salary"] = df["Salary"].apply(increase_salary)
print(emp)

0     79860.0
1     93170.0
2     66550.0
3     73205.0
4    106480.0
5     86515.0
Name: Salary, dtype: float64

In [34]:
#Group the DataFrame by the "Department" column and calculate the mean salary for each department.
groupby=df.groupby("Department")["Salary"].mean()
groupbt1=df.groupby("Department")["Salary"].max()
print(groupby)
print(groupbt1)

Department
HR    75423.333333
IT    93170.000000
Name: Salary, dtype: float64
Department
HR     86515.0
IT    106480.0
Name: Salary, dtype: float64

In [ ]:
#Group the DataFrame by the "Department" column and calculate the mean, min, max, and count of salaries for each department using a pivot table.
res = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc=["mean", "min", "max",'count']
)

print(res)

                    mean      min       max  count
                  Salary   Salary    Salary Salary
Department
HR          75423.333333  66550.0   86515.0      3
IT          93170.000000  79860.0  106480.0      3

In [ ]:
# or Group the DataFrame by the "Department" column and calculate the mean, min, max, and count of salaries for each department using the groupby() method.
multi=df.groupby("Department")["Salary"].agg(
    ["mean", "min", "max"]
    
)
print(multi)

                    mean      min       max
Department
HR          75423.333333  66550.0   86515.0
IT          93170.000000  79860.0  106480.0

In [55]:
df.set_index("Name")

        Department    Salary      state
Name
Alice           IT   79860.0  Bangalore
Bob             IT   93170.0        HYD
Charlie         HR   66550.0    chennai
Chenna          HR   73205.0        HYD
Kesava          IT  106480.0  Bangalore
Reddy           HR   86515.0        HYD

In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Department": ["IT", "HR", "IT"],
    "Salary": [80000, 60000, 90000]
}

df = pd.DataFrame(data)

print(df)

      Name Department  Salary
0    Alice         IT   80000
1      Bob         HR   60000
2  Charlie         IT   90000

In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
import sys

print(sys.executable)

c:\Users\chenn\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\chenn\Downloads\P9-ConsumerComplaints.csv")
print(df.head())
print(df.columns.tolist())
print(df)

  Date Received             Product Name                  Sub Product  \
0    29-07-2013            Consumer Loan                 Vehicle loan
1    29-07-2013  Bank account or service             Checking account
2    29-07-2013  Bank account or service             Checking account
3    29-07-2013  Bank account or service             Checking account
4    29-07-2013                 Mortgage  Conventional fixed mortgage

                                      Issue Sub Issue  \
0                Managing the loan or lease       NaN
1                 Using a debit or ATM card       NaN
2   Account opening, closing, or management       NaN
3                  Deposits and withdrawals       NaN
4  Loan servicing, payments, escrow account       NaN

  Consumer Complaint Narrative Company Public Response  \
0                          NaN                     NaN
1                          NaN                     NaN
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN

                      Company State Name Zip Code            Tags  \
0       Wells Fargo & Company         VA    24540             NaN
1       Wells Fargo & Company         CA    95992  Older American
2           Santander Bank US         NY    10065             NaN
3       Wells Fargo & Company         GA    30084             NaN
4  Franklin Credit Management         CT     6106             NaN

  Consumer Consent Provided Submitted via Date Sent to Company  \
0                       NaN         Phone           30-07-2013
1                       NaN           Web           31-07-2013
2                       NaN           Fax           31-07-2013
3                       NaN           Web           30-07-2013
4                       NaN           Web           30-07-2013

  Company Response to Consumer Timely Response Consumer Disputed  Complaint ID
0      Closed with explanation             Yes                No        468882
1      Closed with explanation             Yes                No        468889
2                       Closed             Yes                No        468879
3      Closed with explanation             Yes                No        468949
4      Closed with explanation             Yes                No        475823
['Date Received', 'Product Name', 'Sub Product', 'Issue', 'Sub Issue', 'Consumer Complaint Narrative', 'Company Public Response', 'Company', 'State Name', 'Zip Code', 'Tags', 'Consumer Consent Provided', 'Submitted via', 'Date Sent to Company', 'Company Response to Consumer', 'Timely Response', 'Consumer Disputed', 'Complaint ID']

C:\Users\chenn\AppData\Local\Temp\ipykernel_560\400634481.py:3: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\chenn\Downloads\P9-ConsumerComplaints.csv")

In [11]:
print(df.columns.tolist())

['Date Received', 'Product Name', 'Sub Product', 'Issue', 'Sub Issue', 'Consumer Complaint Narrative', 'Company Public Response', 'Company', 'State Name', 'Zip Code', 'Tags', 'Consumer Consent Provided', 'Submitted via', 'Date Sent to Company', 'Company Response to Consumer', 'Timely Response', 'Consumer Disputed', 'Complaint ID']